name: Build & Push Accounts

on:
  push:
    branches: [ "master", "section8", "section9" ]
  pull_request:
    branches: [ "master", "section8", "section9" ]

jobs:
  build:

    env:
      IMAGE_BASE: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}

    uses: coderyassin/github-actions-templates/.github/workflows/build.yml@master
    with:
      service-name: accounts
      commit-tag: ${{ github.ref_name }}
      image-base: ${{ IMAGE_BASE }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
